cd fmtlog
BUILD_DIR=${BUILD_DIR:-.build}

ANDROID_NDK_CMAKE="-DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_API=24 -DANDROID_PLATFORM=24 -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_NDK=$ANDROID_NDK_ROOT -DCMAKE_ANDROID_STL_TYPE=c++_static -DCMAKE_CXX_STANDARD=20 -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake -DFMTLOG_IGNORE_SHARED=TRUE -DFMTLOG_SKIP_BENCHMARKS=TRUE -DFMTLOG_SKIP_TEST_BUILD=TRUE -DFMT_HEADER_ONLY=TRUE" 

mkdir -p "$BUILD_DIR" \
  && cd "$BUILD_DIR" \
  && cmake $ANDROID_NDK_CMAKE -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..\
  && cmake --build . -j
